ALTER TABLE pacientes ADD COLUMN cidade TEXT;
ALTER TABLE pacientes ADD COLUMN form_token TEXT;
ALTER TABLE consultas ADD COLUMN refeicoes TEXT;
ALTER TABLE consultas ADD COLUMN objetivo TEXT;
ALTER TABLE consultas ADD COLUMN tmb REAL;
ALTER TABLE consultas ADD COLUMN get_kcal REAL;
ALTER TABLE consultas ADD COLUMN fator_atividade REAL;
CREATE INDEX IF NOT EXISTS idx_pac_token ON pacientes(form_token);
CREATE TABLE IF NOT EXISTS objetivos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL UNIQUE,
  nome_en TEXT,
  nome_es TEXT,
  ativo INTEGER NOT NULL DEFAULT 1,
  posicao INTEGER DEFAULT 0
);
INSERT OR IGNORE INTO objetivos (nome,nome_en,nome_es,posicao) VALUES
 ('Emagrecimento','Weight loss','Pérdida de peso',1),
 ('Definição muscular','Muscle definition','Definición muscular',2),
 ('Ganho de massa muscular','Muscle gain','Ganancia de masa muscular',3),
 ('Manutenção do peso','Weight maintenance','Mantenimiento del peso',4);
CREATE TABLE IF NOT EXISTS form_blocos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chave TEXT NOT NULL UNIQUE,
  titulo_pt TEXT NOT NULL, titulo_en TEXT, titulo_es TEXT,
  ajuda_pt TEXT, ajuda_en TEXT, ajuda_es TEXT,
  ativo INTEGER NOT NULL DEFAULT 1,
  posicao INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS form_campos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bloco_chave TEXT NOT NULL,
  chave TEXT NOT NULL UNIQUE,
  tipo TEXT NOT NULL DEFAULT 'texto',
  rot_pt TEXT NOT NULL, rot_en TEXT, rot_es TEXT,
  dica_pt TEXT, dica_en TEXT, dica_es TEXT,
  opcoes_pt TEXT, opcoes_en TEXT, opcoes_es TEXT,
  obrigatorio INTEGER NOT NULL DEFAULT 1,
  ativo INTEGER NOT NULL DEFAULT 1,
  posicao INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_fcampo_bloco ON form_campos(bloco_chave, posicao);
INSERT OR IGNORE INTO form_blocos (chave,titulo_pt,titulo_en,titulo_es,ajuda_pt,ajuda_en,ajuda_es,posicao) VALUES
 ('quem','Quem é você','About you','Quién eres','Para eu saber com quem estou falando.','So I know who I am talking to.','Para saber con quién estoy hablando.',1),
 ('objetivo','Objetivo e medidas','Goal and measurements','Objetivo y medidas','O ponto de partida.','The starting point.','El punto de partida.',2),
 ('saude','Saúde','Health','Salud','Seja específico — é o que me impede de errar.','Be specific — this is what keeps me from getting it wrong.','Sé específico: es lo que evita que yo me equivoque.',3),
 ('treino','Treino','Training','Entrenamiento','Para eu encaixar a alimentação no seu dia.','So I can fit your meals into your day.','Para encajar tu alimentación en tu día.',4),
 ('rotina','Sua rotina','Your routine','Tu rutina','Os horários de verdade, não os ideais.','The real times, not the ideal ones.','Los horarios reales, no los ideales.',5),
 ('combinado','Combinado','Agreement','Acuerdo','Duas confirmações antes de começarmos.','Two confirmations before we start.','Dos confirmaciones antes de empezar.',6);
INSERT OR IGNORE INTO form_campos (bloco_chave,chave,tipo,rot_pt,rot_en,rot_es,dica_pt,dica_en,dica_es,opcoes_pt,opcoes_en,opcoes_es,obrigatorio,posicao) VALUES
 ('quem','nome','texto','Nome completo','Full name','Nombre completo','','','','','','',1,1),
 ('quem','email','email','E-mail','Email','Correo electrónico','','','','','','',1,2),
 ('quem','telefone','tel','WhatsApp com DDI e DDD','WhatsApp with country code','WhatsApp con código de país','Ex.: +55 51 99999-9999 ou +1 212 555-0000','E.g. +1 212 555-0000','Ej.: +34 600 000 000','','','',1,3),
 ('quem','pais','pais','Onde você mora','Where you live','Dónde vives','','','','','','',1,4),
 ('quem','cidade','texto','Cidade','City','Ciudad','Uso para acertar o fuso horário das nossas conversas.','I use this to get your time zone right.','Lo uso para ajustar tu huso horario.','','','',1,5),
 ('quem','instagram','texto','Instagram','Instagram','Instagram','','','','','','',1,6),
 ('quem','nascimento','data','Data de nascimento','Date of birth','Fecha de nacimiento','','','','','','',1,7),
 ('quem','profissao','texto','Profissão','Occupation','Profesión','','','','','','',1,8),
 ('quem','indicacao','texto','Alguém indicou meu trabalho? Quem?','Did someone refer me to you? Who?','¿Alguien te recomendó mi trabajo? ¿Quién?','Se ninguém indicou, escreva "ninguém".','If nobody did, write "nobody".','Si nadie lo hizo, escribe "nadie".','','','',1,9),
 ('objetivo','objetivo','objetivo','Seu principal objetivo','Your main goal','Tu objetivo principal','','','','','','',1,10),
 ('objetivo','plano_codigo','plano','Plano de interesse','Plan you are interested in','Plan que te interesa','','','','','','',1,11),
 ('objetivo','sexo','radio','Sexo','Sex','Sexo','','','','Feminino|Masculino','Female|Male','Femenino|Masculino',1,12),
 ('objetivo','peso_kg','peso','Peso','Weight','Peso','','','','','','',1,13),
 ('objetivo','altura_cm','altura','Altura','Height','Altura','','','','','','',1,14),
 ('saude','doenca','longo','Tem alguma doença (hipertensão, diabetes, tireoide, lipedema, SOP)? Faz uso de medicação, qual?','Any medical condition (high blood pressure, diabetes, thyroid, lipedema, PCOS)? Any medication?','¿Tienes alguna enfermedad (hipertensión, diabetes, tiroides, lipedema, SOP)? ¿Tomas alguna medicación?','Se não tiver nada, escreva "não".','If none, write "no".','Si no tienes nada, escribe "no".','','','',1,15),
 ('saude','restricao_alimentar','longo','Restrição, alergia, intolerância ou alimento que quer evitar? Qual e com que intensidade?','Any restriction, allergy, intolerance or food you want to avoid? Which one and how severe?','¿Alguna restricción, alergia, intolerancia o alimento que quieras evitar? ¿Cuál y con qué intensidad?','Se não tiver nada, escreva "não".','If none, write "no".','Si no tienes nada, escribe "no".','','','',1,16),
 ('saude','intestino','radio','Como é o seu intestino?','How are your bowel movements?','¿Cómo es tu tránsito intestinal?','','','','Normal|Constipado (fezes ressecadas, de difícil evacuação e não regulares)|Diarreia constante','Normal|Constipated (hard, difficult, irregular)|Frequent diarrhea','Normal|Estreñido (heces secas, difíciles e irregulares)|Diarrea frecuente',1,17),
 ('saude','agua','texto','Quantos litros de água pura você bebe por dia?','How much plain water do you drink per day?','¿Cuántos litros de agua pura bebes al día?','','','','','','',1,18),
 ('saude','suplementos','longo','Já usou ou usa suplementos? Qual, quando e em que dose?','Have you used or do you use supplements? Which, when and what dose?','¿Has usado o usas suplementos? ¿Cuál, cuándo y en qué dosis?','Se nunca usou, escreva "não".','If never, write "no".','Si nunca, escribe "no".','','','',1,19),
 ('saude','suplemento_incluir','texto','Se não usa hoje, quer incluir no plano?','If you do not use any, would you like to include them?','Si hoy no usas, ¿quieres incluirlos en el plan?','','','','','','',1,20),
 ('saude','peptideo','longo','Já usou ou usa peptídeo? Qual, quando e em que dose?','Have you used or do you use peptides? Which, when and what dose?','¿Has usado o usas péptidos? ¿Cuál, cuándo y en qué dosis?','Se nunca usou, escreva "não".','If never, write "no".','Si nunca, escribe "no".','','','',1,21),
 ('saude','restricao_fisica','longo','Tem alguma restrição física? Qual?','Any physical limitation? Which?','¿Tienes alguna limitación física? ¿Cuál?','Se não tiver nada, escreva "não".','If none, write "no".','Si no tienes nada, escribe "no".','','','',1,22),
 ('treino','atividade','texto','Qual atividade física você pratica ou quer praticar?','What physical activity do you do or want to do?','¿Qué actividad física practicas o quieres practicar?','','','','','','',1,23),
 ('treino','frequencia','texto','Quantas vezes por semana?','How many times per week?','¿Cuántas veces por semana?','','','','','','',1,24),
 ('treino','horario_treino','texto','Que horas você treina ou pretende treinar?','What time do you train or plan to train?','¿A qué hora entrenas o piensas entrenar?','','','','','','',1,25),
 ('treino','segunda_atividade','longo','Faz uma segunda atividade no dia? Conte qual e em que horário.','Do you do a second activity in the day? Tell me which and when.','¿Haces una segunda actividad al día? Cuéntame cuál y a qué hora.','Se não fizer, escreva "não".','If not, write "no".','Si no, escribe "no".','','','',1,26),
 ('rotina','acorda','hora','Que horas acorda','Wake up time','A qué hora te levantas','','','','','','',1,27),
 ('rotina','cafe','hora','Café da manhã','Breakfast','Desayuno','','','','','','',1,28),
 ('rotina','almoco','hora','Almoço','Lunch','Almuerzo','','','','','','',1,29),
 ('rotina','lanche','hora','Lanche','Snack','Merienda','','','','','','',1,30),
 ('rotina','jantar','hora','Jantar','Dinner','Cena','','','','','','',1,31),
 ('rotina','dorme','hora','Que horas dorme','Bedtime','A qué hora te acuestas','','','','','','',1,32),
 ('rotina','pref_jantar','radio','Sua preferência no jantar','Your preference for dinner','Tu preferencia para la cena','','','','Comida como no almoço (ex.: arroz e frango)|Lanche como no café da manhã (ex.: pão com ovo)','A full meal like lunch (e.g. rice and chicken)|A light meal like breakfast (e.g. eggs on toast)','Comida como el almuerzo (ej.: arroz con pollo)|Algo ligero como el desayuno (ej.: pan con huevo)',1,33),
 ('rotina','manter','longo','Algum alimento que você faz questão de manter no plano? Qual?','Any food you really want to keep in your plan? Which?','¿Algún alimento que quieras mantener sí o sí en el plan? ¿Cuál?','Se não tiver, escreva "não".','If none, write "no".','Si no, escribe "no".','','','',1,34),
 ('rotina','relevante','longo','Tem algum detalhe que você acha importante eu saber?','Anything else you think I should know?','¿Hay algo más que creas importante que yo sepa?','Se não tiver, escreva "não".','If none, write "no".','Si no, escribe "no".','','','',1,35),
 ('combinado','ciente_rotina','radio','Você está ciente de que precisará me passar sua rotina pelo WhatsApp diariamente?','Do you understand that you will need to send me your daily routine on WhatsApp?','¿Entiendes que tendrás que pasarme tu rutina por WhatsApp todos los días?','','','','Sim|Não','Yes|No','Sí|No',1,36),
 ('combinado','ciente_texto','radio','Tenho uma limitação auditiva severa e tenho dificuldade com áudios no WhatsApp. Posso contar com você para mandar as mensagens em texto?','I have severe hearing loss and struggle with voice notes on WhatsApp. Can I count on you to send text messages?','Tengo una pérdida auditiva severa y me cuesta escuchar audios en WhatsApp. ¿Puedo contar contigo para que escribas los mensajes?','','','','Sim|Não','Yes|No','Sí|No',1,37);
CREATE TABLE IF NOT EXISTS fusos_lugar (
  chave TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  pais TEXT,
  fuso TEXT NOT NULL
);
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('alabama','Alabama','US','America/Chicago'),
 ('al','AL','US','America/Chicago'),
 ('alaska','Alaska','US','America/Anchorage'),
 ('ak','AK','US','America/Anchorage'),
 ('arizona','Arizona','US','America/Phoenix'),
 ('az','AZ','US','America/Phoenix'),
 ('arkansas','Arkansas','US','America/Chicago'),
 ('ar','AR','US','America/Chicago'),
 ('california','California','US','America/Los_Angeles'),
 ('ca','CA','US','America/Los_Angeles'),
 ('colorado','Colorado','US','America/Denver'),
 ('co','CO','US','America/Denver'),
 ('connecticut','Connecticut','US','America/New_York'),
 ('ct','CT','US','America/New_York'),
 ('delaware','Delaware','US','America/New_York'),
 ('de','DE','US','America/New_York'),
 ('district of columbia','District of Columbia','US','America/New_York'),
 ('dc','DC','US','America/New_York'),
 ('florida','Florida','US','America/New_York'),
 ('fl','FL','US','America/New_York'),
 ('georgia','Georgia','US','America/New_York'),
 ('ga','GA','US','America/New_York'),
 ('hawaii','Hawaii','US','Pacific/Honolulu'),
 ('hi','HI','US','Pacific/Honolulu'),
 ('idaho','Idaho','US','America/Denver'),
 ('id','ID','US','America/Denver'),
 ('illinois','Illinois','US','America/Chicago'),
 ('il','IL','US','America/Chicago'),
 ('indiana','Indiana','US','America/New_York'),
 ('in','IN','US','America/New_York'),
 ('iowa','Iowa','US','America/Chicago'),
 ('ia','IA','US','America/Chicago'),
 ('kansas','Kansas','US','America/Chicago'),
 ('ks','KS','US','America/Chicago'),
 ('kentucky','Kentucky','US','America/New_York'),
 ('ky','KY','US','America/New_York'),
 ('louisiana','Louisiana','US','America/Chicago'),
 ('la','LA','US','America/Chicago'),
 ('maine','Maine','US','America/New_York'),
 ('me','ME','US','America/New_York'),
 ('maryland','Maryland','US','America/New_York'),
 ('md','MD','US','America/New_York'),
 ('massachusetts','Massachusetts','US','America/New_York'),
 ('ma','MA','US','America/New_York'),
 ('michigan','Michigan','US','America/New_York'),
 ('mi','MI','US','America/New_York'),
 ('minnesota','Minnesota','US','America/Chicago'),
 ('mn','MN','US','America/Chicago'),
 ('mississippi','Mississippi','US','America/Chicago'),
 ('ms','MS','US','America/Chicago'),
 ('missouri','Missouri','US','America/Chicago'),
 ('mo','MO','US','America/Chicago'),
 ('montana','Montana','US','America/Denver'),
 ('mt','MT','US','America/Denver'),
 ('nebraska','Nebraska','US','America/Chicago'),
 ('ne','NE','US','America/Chicago'),
 ('nevada','Nevada','US','America/Los_Angeles'),
 ('nv','NV','US','America/Los_Angeles'),
 ('new hampshire','New Hampshire','US','America/New_York'),
 ('nh','NH','US','America/New_York'),
 ('new jersey','New Jersey','US','America/New_York'),
 ('nj','NJ','US','America/New_York'),
 ('new mexico','New Mexico','US','America/Denver'),
 ('nm','NM','US','America/Denver'),
 ('new york','New York','US','America/New_York'),
 ('ny','NY','US','America/New_York'),
 ('north carolina','North Carolina','US','America/New_York'),
 ('nc','NC','US','America/New_York'),
 ('north dakota','North Dakota','US','America/Chicago'),
 ('nd','ND','US','America/Chicago'),
 ('ohio','Ohio','US','America/New_York'),
 ('oh','OH','US','America/New_York'),
 ('oklahoma','Oklahoma','US','America/Chicago'),
 ('ok','OK','US','America/Chicago'),
 ('oregon','Oregon','US','America/Los_Angeles'),
 ('or','OR','US','America/Los_Angeles'),
 ('pennsylvania','Pennsylvania','US','America/New_York'),
 ('pa','PA','US','America/New_York'),
 ('rhode island','Rhode Island','US','America/New_York'),
 ('ri','RI','US','America/New_York'),
 ('south carolina','South Carolina','US','America/New_York'),
 ('sc','SC','US','America/New_York'),
 ('south dakota','South Dakota','US','America/Chicago'),
 ('sd','SD','US','America/Chicago'),
 ('tennessee','Tennessee','US','America/Chicago'),
 ('tn','TN','US','America/Chicago'),
 ('texas','Texas','US','America/Chicago'),
 ('tx','TX','US','America/Chicago'),
 ('utah','Utah','US','America/Denver'),
 ('ut','UT','US','America/Denver'),
 ('vermont','Vermont','US','America/New_York'),
 ('vt','VT','US','America/New_York'),
 ('virginia','Virginia','US','America/New_York'),
 ('va','VA','US','America/New_York'),
 ('washington','Washington','US','America/Los_Angeles'),
 ('wa','WA','US','America/Los_Angeles'),
 ('west virginia','West Virginia','US','America/New_York'),
 ('wv','WV','US','America/New_York'),
 ('wisconsin','Wisconsin','US','America/Chicago'),
 ('wi','WI','US','America/Chicago'),
 ('wyoming','Wyoming','US','America/Denver'),
 ('wy','WY','US','America/Denver'),
 ('puerto rico','Puerto Rico','US','America/Puerto_Rico'),
 ('pr','PR','US','America/Puerto_Rico'),
 ('nova york','Nova York','US','America/New_York'),
 ('brooklyn','Brooklyn','US','America/New_York'),
 ('queens','Queens','US','America/New_York'),
 ('bronx','Bronx','US','America/New_York'),
 ('manhattan','Manhattan','US','America/New_York'),
 ('staten island','Staten Island','US','America/New_York'),
 ('newark','Newark','US','America/New_York'),
 ('jersey city','Jersey City','US','America/New_York'),
 ('boston','Boston','US','America/New_York'),
 ('philadelphia','Philadelphia','US','America/New_York'),
 ('filadelfia','Filadelfia','US','America/New_York'),
 ('pittsburgh','Pittsburgh','US','America/New_York'),
 ('baltimore','Baltimore','US','America/New_York'),
 ('atlanta','Atlanta','US','America/New_York'),
 ('miami','Miami','US','America/New_York'),
 ('orlando','Orlando','US','America/New_York');
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('tampa','Tampa','US','America/New_York'),
 ('jacksonville','Jacksonville','US','America/New_York'),
 ('fort lauderdale','Fort Lauderdale','US','America/New_York'),
 ('boca raton','Boca Raton','US','America/New_York'),
 ('west palm beach','West Palm Beach','US','America/New_York'),
 ('naples','Naples','US','America/New_York'),
 ('sarasota','Sarasota','US','America/New_York'),
 ('cape coral','Cape Coral','US','America/New_York'),
 ('charlotte','Charlotte','US','America/New_York'),
 ('raleigh','Raleigh','US','America/New_York'),
 ('durham','Durham','US','America/New_York'),
 ('richmond','Richmond','US','America/New_York'),
 ('virginia beach','Virginia Beach','US','America/New_York'),
 ('norfolk','Norfolk','US','America/New_York'),
 ('columbus','Columbus','US','America/New_York'),
 ('cleveland','Cleveland','US','America/New_York'),
 ('cincinnati','Cincinnati','US','America/New_York'),
 ('detroit','Detroit','US','America/New_York'),
 ('grand rapids','Grand Rapids','US','America/New_York'),
 ('buffalo','Buffalo','US','America/New_York'),
 ('rochester','Rochester','US','America/New_York'),
 ('syracuse','Syracuse','US','America/New_York'),
 ('albany','Albany','US','America/New_York'),
 ('hartford','Hartford','US','America/New_York'),
 ('stamford','Stamford','US','America/New_York'),
 ('providence','Providence','US','America/New_York'),
 ('portland maine','Portland Maine','US','America/New_York'),
 ('worcester','Worcester','US','America/New_York'),
 ('springfield','Springfield','US','America/New_York'),
 ('allentown','Allentown','US','America/New_York'),
 ('harrisburg','Harrisburg','US','America/New_York'),
 ('wilmington','Wilmington','US','America/New_York'),
 ('greensboro','Greensboro','US','America/New_York'),
 ('winston salem','Winston-Salem','US','America/New_York'),
 ('charleston','Charleston','US','America/New_York'),
 ('columbia','Columbia','US','America/New_York'),
 ('savannah','Savannah','US','America/New_York'),
 ('augusta','Augusta','US','America/New_York'),
 ('lexington','Lexington','US','America/New_York'),
 ('louisville','Louisville','US','America/New_York'),
 ('indianapolis','Indianapolis','US','America/New_York'),
 ('fort myers','Fort Myers','US','America/New_York'),
 ('daytona beach','Daytona Beach','US','America/New_York'),
 ('gainesville','Gainesville','US','America/New_York'),
 ('tallahassee','Tallahassee','US','America/New_York'),
 ('clearwater','Clearwater','US','America/New_York'),
 ('st petersburg','St Petersburg','US','America/New_York'),
 ('saint petersburg','Saint Petersburg','US','America/New_York'),
 ('hialeah','Hialeah','US','America/New_York'),
 ('coral gables','Coral Gables','US','America/New_York'),
 ('doral','Doral','US','America/New_York'),
 ('kissimmee','Kissimmee','US','America/New_York'),
 ('pompano beach','Pompano Beach','US','America/New_York'),
 ('hollywood','Hollywood','US','America/New_York'),
 ('deerfield beach','Deerfield Beach','US','America/New_York'),
 ('weston','Weston','US','America/New_York'),
 ('danbury','Danbury','US','America/New_York'),
 ('new haven','New Haven','US','America/New_York'),
 ('bridgeport','Bridgeport','US','America/New_York'),
 ('yonkers','Yonkers','US','America/New_York'),
 ('long island','Long Island','US','America/New_York'),
 ('elizabeth','Elizabeth','US','America/New_York'),
 ('paterson','Paterson','US','America/New_York'),
 ('trenton','Trenton','US','America/New_York'),
 ('framingham','Framingham','US','America/New_York'),
 ('chicago','Chicago','US','America/Chicago'),
 ('houston','Houston','US','America/Chicago'),
 ('dallas','Dallas','US','America/Chicago'),
 ('fort worth','Fort Worth','US','America/Chicago'),
 ('austin','Austin','US','America/Chicago'),
 ('san antonio','San Antonio','US','America/Chicago'),
 ('nashville','Nashville','US','America/Chicago'),
 ('memphis','Memphis','US','America/Chicago'),
 ('new orleans','New Orleans','US','America/Chicago'),
 ('oklahoma city','Oklahoma City','US','America/Chicago'),
 ('tulsa','Tulsa','US','America/Chicago'),
 ('kansas city','Kansas City','US','America/Chicago'),
 ('st louis','St Louis','US','America/Chicago'),
 ('saint louis','Saint Louis','US','America/Chicago'),
 ('milwaukee','Milwaukee','US','America/Chicago'),
 ('minneapolis','Minneapolis','US','America/Chicago'),
 ('saint paul','Saint Paul','US','America/Chicago'),
 ('omaha','Omaha','US','America/Chicago'),
 ('des moines','Des Moines','US','America/Chicago'),
 ('little rock','Little Rock','US','America/Chicago'),
 ('birmingham','Birmingham','US','America/Chicago'),
 ('montgomery','Montgomery','US','America/Chicago'),
 ('mobile','Mobile','US','America/Chicago'),
 ('jackson','Jackson','US','America/Chicago'),
 ('baton rouge','Baton Rouge','US','America/Chicago'),
 ('wichita','Wichita','US','America/Chicago'),
 ('madison','Madison','US','America/Chicago'),
 ('lincoln','Lincoln','US','America/Chicago'),
 ('fargo','Fargo','US','America/Chicago'),
 ('sioux falls','Sioux Falls','US','America/Chicago'),
 ('shreveport','Shreveport','US','America/Chicago'),
 ('lubbock','Lubbock','US','America/Chicago'),
 ('irving','Irving','US','America/Chicago'),
 ('plano','Plano','US','America/Chicago'),
 ('frisco','Frisco','US','America/Chicago'),
 ('arlington','Arlington','US','America/Chicago'),
 ('katy','Katy','US','America/Chicago'),
 ('sugar land','Sugar Land','US','America/Chicago'),
 ('the woodlands','The Woodlands','US','America/Chicago'),
 ('mcallen','McAllen','US','America/Chicago'),
 ('el paso','El Paso','US','America/Chicago'),
 ('laredo','Laredo','US','America/Chicago'),
 ('corpus christi','Corpus Christi','US','America/Chicago'),
 ('galveston','Galveston','US','America/Chicago'),
 ('knoxville','Knoxville','US','America/Chicago'),
 ('chattanooga','Chattanooga','US','America/Chicago'),
 ('clarksville','Clarksville','US','America/Chicago'),
 ('murfreesboro','Murfreesboro','US','America/Chicago'),
 ('rockford','Rockford','US','America/Chicago'),
 ('naperville','Naperville','US','America/Chicago'),
 ('aurora illinois','Aurora Illinois','US','America/Chicago'),
 ('denver','Denver','US','America/Denver'),
 ('colorado springs','Colorado Springs','US','America/Denver'),
 ('boulder','Boulder','US','America/Denver'),
 ('aurora','Aurora','US','America/Denver');
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('salt lake city','Salt Lake City','US','America/Denver'),
 ('provo','Provo','US','America/Denver'),
 ('albuquerque','Albuquerque','US','America/Denver'),
 ('santa fe','Santa Fe','US','America/Denver'),
 ('boise','Boise','US','America/Denver'),
 ('billings','Billings','US','America/Denver'),
 ('bozeman','Bozeman','US','America/Denver'),
 ('cheyenne','Cheyenne','US','America/Denver'),
 ('fort collins','Fort Collins','US','America/Denver'),
 ('pueblo','Pueblo','US','America/Denver'),
 ('las cruces','Las Cruces','US','America/Denver'),
 ('ogden','Ogden','US','America/Denver'),
 ('los angeles','Los Angeles','US','America/Los_Angeles'),
 ('san francisco','San Francisco','US','America/Los_Angeles'),
 ('san diego','San Diego','US','America/Los_Angeles'),
 ('san jose','San Jose','US','America/Los_Angeles'),
 ('sacramento','Sacramento','US','America/Los_Angeles'),
 ('oakland','Oakland','US','America/Los_Angeles'),
 ('fresno','Fresno','US','America/Los_Angeles'),
 ('long beach','Long Beach','US','America/Los_Angeles'),
 ('santa monica','Santa Monica','US','America/Los_Angeles'),
 ('beverly hills','Beverly Hills','US','America/Los_Angeles'),
 ('pasadena','Pasadena','US','America/Los_Angeles'),
 ('anaheim','Anaheim','US','America/Los_Angeles'),
 ('irvine','Irvine','US','America/Los_Angeles'),
 ('riverside','Riverside','US','America/Los_Angeles'),
 ('bakersfield','Bakersfield','US','America/Los_Angeles'),
 ('stockton','Stockton','US','America/Los_Angeles'),
 ('seattle','Seattle','US','America/Los_Angeles'),
 ('tacoma','Tacoma','US','America/Los_Angeles'),
 ('spokane','Spokane','US','America/Los_Angeles'),
 ('bellevue','Bellevue','US','America/Los_Angeles'),
 ('vancouver washington','Vancouver Washington','US','America/Los_Angeles'),
 ('portland','Portland','US','America/Los_Angeles'),
 ('eugene','Eugene','US','America/Los_Angeles'),
 ('salem','Salem','US','America/Los_Angeles'),
 ('bend','Bend','US','America/Los_Angeles'),
 ('las vegas','Las Vegas','US','America/Los_Angeles'),
 ('reno','Reno','US','America/Los_Angeles'),
 ('henderson','Henderson','US','America/Los_Angeles'),
 ('santa barbara','Santa Barbara','US','America/Los_Angeles'),
 ('santa clara','Santa Clara','US','America/Los_Angeles'),
 ('sunnyvale','Sunnyvale','US','America/Los_Angeles'),
 ('palo alto','Palo Alto','US','America/Los_Angeles'),
 ('berkeley','Berkeley','US','America/Los_Angeles'),
 ('chula vista','Chula Vista','US','America/Los_Angeles'),
 ('fremont','Fremont','US','America/Los_Angeles'),
 ('modesto','Modesto','US','America/Los_Angeles'),
 ('oxnard','Oxnard','US','America/Los_Angeles'),
 ('ontario','Ontario','US','America/Los_Angeles'),
 ('glendale','Glendale','US','America/Los_Angeles'),
 ('huntington beach','Huntington Beach','US','America/Los_Angeles'),
 ('newport beach','Newport Beach','US','America/Los_Angeles'),
 ('san bernardino','San Bernardino','US','America/Los_Angeles'),
 ('torrance','Torrance','US','America/Los_Angeles'),
 ('burbank','Burbank','US','America/Los_Angeles'),
 ('culver city','Culver City','US','America/Los_Angeles'),
 ('hollywood california','Hollywood California','US','America/Los_Angeles'),
 ('malibu','Malibu','US','America/Los_Angeles'),
 ('temecula','Temecula','US','America/Los_Angeles'),
 ('phoenix','Phoenix','US','America/Phoenix'),
 ('tucson','Tucson','US','America/Phoenix'),
 ('mesa','Mesa','US','America/Phoenix'),
 ('scottsdale','Scottsdale','US','America/Phoenix'),
 ('chandler','Chandler','US','America/Phoenix'),
 ('gilbert','Gilbert','US','America/Phoenix'),
 ('glendale arizona','Glendale Arizona','US','America/Phoenix'),
 ('tempe','Tempe','US','America/Phoenix'),
 ('peoria','Peoria','US','America/Phoenix'),
 ('yuma','Yuma','US','America/Phoenix'),
 ('anchorage','Anchorage','US','America/Anchorage'),
 ('fairbanks','Fairbanks','US','America/Anchorage'),
 ('juneau','Juneau','US','America/Anchorage'),
 ('honolulu','Honolulu','US','Pacific/Honolulu'),
 ('maui','Maui','US','Pacific/Honolulu'),
 ('kona','Kona','US','Pacific/Honolulu'),
 ('hilo','Hilo','US','Pacific/Honolulu'),
 ('acre','Acre','Brasil','America/Rio_Branco'),
 ('ac','AC','Brasil','America/Rio_Branco'),
 ('alagoas','Alagoas','Brasil','America/Maceio'),
 ('amapa','Amapá','Brasil','America/Belem'),
 ('ap','AP','Brasil','America/Belem'),
 ('amazonas','Amazonas','Brasil','America/Manaus'),
 ('am','AM','Brasil','America/Manaus'),
 ('bahia','Bahia','Brasil','America/Bahia'),
 ('ba','BA','Brasil','America/Bahia'),
 ('ceara','Ceará','Brasil','America/Fortaleza'),
 ('ce','CE','Brasil','America/Fortaleza'),
 ('distrito federal','Distrito Federal','Brasil','America/Sao_Paulo'),
 ('df','DF','Brasil','America/Sao_Paulo'),
 ('espirito santo','Espírito Santo','Brasil','America/Sao_Paulo'),
 ('es','ES','Brasil','America/Sao_Paulo'),
 ('goias','Goiás','Brasil','America/Sao_Paulo'),
 ('go','GO','Brasil','America/Sao_Paulo'),
 ('maranhao','Maranhão','Brasil','America/Fortaleza'),
 ('mato grosso','Mato Grosso','Brasil','America/Cuiaba'),
 ('mato grosso do sul','Mato Grosso do Sul','Brasil','America/Campo_Grande'),
 ('minas gerais','Minas Gerais','Brasil','America/Sao_Paulo'),
 ('mg','MG','Brasil','America/Sao_Paulo'),
 ('para','Pará','Brasil','America/Belem'),
 ('paraiba','Paraíba','Brasil','America/Fortaleza'),
 ('pb','PB','Brasil','America/Fortaleza'),
 ('parana','Paraná','Brasil','America/Sao_Paulo'),
 ('pernambuco','Pernambuco','Brasil','America/Recife'),
 ('pe','PE','Brasil','America/Recife'),
 ('piaui','Piauí','Brasil','America/Fortaleza'),
 ('pi','PI','Brasil','America/Fortaleza'),
 ('rio de janeiro','Rio de Janeiro','Brasil','America/Sao_Paulo'),
 ('rj','RJ','Brasil','America/Sao_Paulo'),
 ('rio grande do norte','Rio Grande do Norte','Brasil','America/Fortaleza'),
 ('rn','RN','Brasil','America/Fortaleza'),
 ('rio grande do sul','Rio Grande do Sul','Brasil','America/Sao_Paulo'),
 ('rs','RS','Brasil','America/Sao_Paulo'),
 ('rondonia','Rondônia','Brasil','America/Porto_Velho'),
 ('ro','RO','Brasil','America/Porto_Velho'),
 ('roraima','Roraima','Brasil','America/Boa_Vista'),
 ('rr','RR','Brasil','America/Boa_Vista'),
 ('santa catarina','Santa Catarina','Brasil','America/Sao_Paulo'),
 ('sao paulo','São Paulo','Brasil','America/Sao_Paulo'),
 ('sp','SP','Brasil','America/Sao_Paulo');
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('sergipe','Sergipe','Brasil','America/Maceio'),
 ('se','SE','Brasil','America/Maceio'),
 ('tocantins','Tocantins','Brasil','America/Araguaina'),
 ('to','TO','Brasil','America/Araguaina'),
 ('rio branco','Rio Branco','Brasil','America/Rio_Branco'),
 ('maceio','Maceió','Brasil','America/Maceio'),
 ('macapa','Macapá','Brasil','America/Belem'),
 ('manaus','Manaus','Brasil','America/Manaus'),
 ('salvador','Salvador','Brasil','America/Bahia'),
 ('fortaleza','Fortaleza','Brasil','America/Fortaleza'),
 ('brasilia','Brasília','Brasil','America/Sao_Paulo'),
 ('vitoria','Vitória','Brasil','America/Sao_Paulo'),
 ('goiania','Goiânia','Brasil','America/Sao_Paulo'),
 ('sao luis','São Luís','Brasil','America/Fortaleza'),
 ('cuiaba','Cuiabá','Brasil','America/Cuiaba'),
 ('campo grande','Campo Grande','Brasil','America/Campo_Grande'),
 ('belo horizonte','Belo Horizonte','Brasil','America/Sao_Paulo'),
 ('belem','Belém','Brasil','America/Belem'),
 ('joao pessoa','João Pessoa','Brasil','America/Fortaleza'),
 ('curitiba','Curitiba','Brasil','America/Sao_Paulo'),
 ('recife','Recife','Brasil','America/Recife'),
 ('teresina','Teresina','Brasil','America/Fortaleza'),
 ('natal','Natal','Brasil','America/Fortaleza'),
 ('porto alegre','Porto Alegre','Brasil','America/Sao_Paulo'),
 ('porto velho','Porto Velho','Brasil','America/Porto_Velho'),
 ('boa vista','Boa Vista','Brasil','America/Boa_Vista'),
 ('florianopolis','Florianópolis','Brasil','America/Sao_Paulo'),
 ('aracaju','Aracaju','Brasil','America/Maceio'),
 ('palmas','Palmas','Brasil','America/Araguaina'),
 ('campinas','Campinas','Brasil','America/Sao_Paulo'),
 ('santos','Santos','Brasil','America/Sao_Paulo'),
 ('guarulhos','Guarulhos','Brasil','America/Sao_Paulo'),
 ('sorocaba','Sorocaba','Brasil','America/Sao_Paulo'),
 ('ribeirao preto','Ribeirão Preto','Brasil','America/Sao_Paulo'),
 ('niteroi','Niterói','Brasil','America/Sao_Paulo'),
 ('caxias do sul','Caxias do Sul','Brasil','America/Sao_Paulo'),
 ('pelotas','Pelotas','Brasil','America/Sao_Paulo'),
 ('santa maria','Santa Maria','Brasil','America/Sao_Paulo'),
 ('canoas','Canoas','Brasil','America/Sao_Paulo'),
 ('dom pedrito','Dom Pedrito','Brasil','America/Sao_Paulo'),
 ('bage','Bagé','Brasil','America/Sao_Paulo'),
 ('uberlandia','Uberlândia','Brasil','America/Sao_Paulo'),
 ('londrina','Londrina','Brasil','America/Sao_Paulo'),
 ('maringa','Maringá','Brasil','America/Sao_Paulo'),
 ('joinville','Joinville','Brasil','America/Sao_Paulo'),
 ('blumenau','Blumenau','Brasil','America/Sao_Paulo'),
 ('balneario camboriu','Balneário Camboriú','Brasil','America/Sao_Paulo'),
 ('itajai','Itajaí','Brasil','America/Sao_Paulo'),
 ('chapeco','Chapecó','Brasil','America/Sao_Paulo'),
 ('juiz de fora','Juiz de Fora','Brasil','America/Sao_Paulo'),
 ('contagem','Contagem','Brasil','America/Sao_Paulo'),
 ('betim','Betim','Brasil','America/Sao_Paulo'),
 ('osasco','Osasco','Brasil','America/Sao_Paulo'),
 ('santo andre','Santo André','Brasil','America/Sao_Paulo'),
 ('sao bernardo do campo','São Bernardo do Campo','Brasil','America/Sao_Paulo'),
 ('jundiai','Jundiaí','Brasil','America/Sao_Paulo'),
 ('bauru','Bauru','Brasil','America/Sao_Paulo'),
 ('franca','Franca','Brasil','America/Sao_Paulo'),
 ('piracicaba','Piracicaba','Brasil','America/Sao_Paulo'),
 ('serra','Serra','Brasil','America/Sao_Paulo'),
 ('vila velha','Vila Velha','Brasil','America/Sao_Paulo'),
 ('cariacica','Cariacica','Brasil','America/Sao_Paulo'),
 ('anapolis','Anápolis','Brasil','America/Sao_Paulo'),
 ('aparecida de goiania','Aparecida de Goiânia','Brasil','America/Sao_Paulo'),
 ('caruaru','Caruaru','Brasil','America/Recife'),
 ('olinda','Olinda','Brasil','America/Recife'),
 ('jaboatao dos guararapes','Jaboatão dos Guararapes','Brasil','America/Recife'),
 ('feira de santana','Feira de Santana','Brasil','America/Bahia'),
 ('camacari','Camaçari','Brasil','America/Bahia'),
 ('vitoria da conquista','Vitória da Conquista','Brasil','America/Bahia'),
 ('petrolina','Petrolina','Brasil','America/Recife'),
 ('juazeiro do norte','Juazeiro do Norte','Brasil','America/Fortaleza'),
 ('mossoro','Mossoró','Brasil','America/Fortaleza'),
 ('campina grande','Campina Grande','Brasil','America/Fortaleza'),
 ('imperatriz','Imperatriz','Brasil','America/Fortaleza'),
 ('maraba','Marabá','Brasil','America/Belem'),
 ('santarem','Santarém','Brasil','America/Santarem'),
 ('ananindeua','Ananindeua','Brasil','America/Belem'),
 ('rondonopolis','Rondonópolis','Brasil','America/Cuiaba'),
 ('dourados','Dourados','Brasil','America/Campo_Grande'),
 ('gramado','Gramado','Brasil','America/Sao_Paulo'),
 ('passo fundo','Passo Fundo','Brasil','America/Sao_Paulo'),
 ('novo hamburgo','Novo Hamburgo','Brasil','America/Sao_Paulo'),
 ('sao leopoldo','São Leopoldo','Brasil','America/Sao_Paulo'),
 ('rio grande','Rio Grande','Brasil','America/Sao_Paulo'),
 ('portugal','Portugal','Portugal','Europe/Lisbon'),
 ('lisboa','Lisboa','Portugal','Europe/Lisbon'),
 ('lisbon','Lisbon','Portugal','Europe/Lisbon'),
 ('porto','Porto','Portugal','Europe/Lisbon'),
 ('braga','Braga','Portugal','Europe/Lisbon'),
 ('coimbra','Coimbra','Portugal','Europe/Lisbon'),
 ('faro','Faro','Portugal','Europe/Lisbon'),
 ('cascais','Cascais','Portugal','Europe/Lisbon'),
 ('sintra','Sintra','Portugal','Europe/Lisbon'),
 ('aveiro','Aveiro','Portugal','Europe/Lisbon'),
 ('setubal','Setúbal','Portugal','Europe/Lisbon'),
 ('funchal','Funchal','Portugal','Europe/Lisbon'),
 ('albufeira','Albufeira','Portugal','Europe/Lisbon'),
 ('guimaraes','Guimarães','Portugal','Europe/Lisbon'),
 ('viseu','Viseu','Portugal','Europe/Lisbon'),
 ('leiria','Leiria','Portugal','Europe/Lisbon'),
 ('almada','Almada','Portugal','Europe/Lisbon'),
 ('amadora','Amadora','Portugal','Europe/Lisbon'),
 ('inglaterra','Inglaterra','Inglaterra','Europe/London'),
 ('england','England','Inglaterra','Europe/London'),
 ('reino unido','Reino Unido','Inglaterra','Europe/London'),
 ('united kingdom','United Kingdom','Inglaterra','Europe/London'),
 ('londres','Londres','Inglaterra','Europe/London'),
 ('london','London','Inglaterra','Europe/London'),
 ('manchester','Manchester','Inglaterra','Europe/London'),
 ('liverpool','Liverpool','Inglaterra','Europe/London'),
 ('leeds','Leeds','Inglaterra','Europe/London'),
 ('bristol','Bristol','Inglaterra','Europe/London'),
 ('sheffield','Sheffield','Inglaterra','Europe/London'),
 ('nottingham','Nottingham','Inglaterra','Europe/London'),
 ('leicester','Leicester','Inglaterra','Europe/London'),
 ('glasgow','Glasgow','Inglaterra','Europe/London'),
 ('edinburgh','Edinburgh','Inglaterra','Europe/London'),
 ('edimburgo','Edimburgo','Inglaterra','Europe/London'),
 ('cardiff','Cardiff','Inglaterra','Europe/London');
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('belfast','Belfast','Inglaterra','Europe/London'),
 ('newcastle','Newcastle','Inglaterra','Europe/London'),
 ('brighton','Brighton','Inglaterra','Europe/London'),
 ('oxford','Oxford','Inglaterra','Europe/London'),
 ('cambridge','Cambridge','Inglaterra','Europe/London'),
 ('southampton','Southampton','Inglaterra','Europe/London'),
 ('reading','Reading','Inglaterra','Europe/London'),
 ('coventry','Coventry','Inglaterra','Europe/London'),
 ('luton','Luton','Inglaterra','Europe/London'),
 ('milton keynes','Milton Keynes','Inglaterra','Europe/London'),
 ('toronto','Toronto','Canadá','America/Toronto'),
 ('ottawa','Ottawa','Canadá','America/Toronto'),
 ('montreal','Montreal','Canadá','America/Toronto'),
 ('quebec','Quebec','Canadá','America/Toronto'),
 ('hamilton','Hamilton','Canadá','America/Toronto'),
 ('london ontario','London Ontario','Canadá','America/Toronto'),
 ('kingston','Kingston','Canadá','America/Toronto'),
 ('mississauga','Mississauga','Canadá','America/Toronto'),
 ('brampton','Brampton','Canadá','America/Toronto'),
 ('markham','Markham','Canadá','America/Toronto'),
 ('niagara falls','Niagara Falls','Canadá','America/Toronto'),
 ('windsor','Windsor','Canadá','America/Toronto'),
 ('halifax','Halifax','Canadá','America/Toronto'),
 ('vancouver','Vancouver','Canadá','America/Vancouver'),
 ('victoria','Victoria','Canadá','America/Vancouver'),
 ('surrey','Surrey','Canadá','America/Vancouver'),
 ('burnaby','Burnaby','Canadá','America/Vancouver'),
 ('kelowna','Kelowna','Canadá','America/Vancouver'),
 ('richmond bc','Richmond BC','Canadá','America/Vancouver'),
 ('calgary','Calgary','Canadá','America/Edmonton'),
 ('edmonton','Edmonton','Canadá','America/Edmonton'),
 ('red deer','Red Deer','Canadá','America/Edmonton'),
 ('lethbridge','Lethbridge','Canadá','America/Edmonton'),
 ('winnipeg','Winnipeg','Canadá','America/Winnipeg'),
 ('regina','Regina','Canadá','America/Winnipeg'),
 ('saskatoon','Saskatoon','Canadá','America/Winnipeg'),
 ('colombia','Colômbia','Colômbia','America/Bogota'),
 ('bogota','Bogotá','Colômbia','America/Bogota'),
 ('medellin','Medellín','Colômbia','America/Bogota'),
 ('cali','Cali','Colômbia','America/Bogota'),
 ('barranquilla','Barranquilla','Colômbia','America/Bogota'),
 ('cartagena','Cartagena','Colômbia','America/Bogota'),
 ('bucaramanga','Bucaramanga','Colômbia','America/Bogota'),
 ('pereira','Pereira','Colômbia','America/Bogota'),
 ('santa marta','Santa Marta','Colômbia','America/Bogota'),
 ('manizales','Manizales','Colômbia','America/Bogota'),
 ('cucuta','Cúcuta','Colômbia','America/Bogota'),
 ('luxemburgo','Luxemburgo','Luxemburgo','Europe/Luxembourg'),
 ('luxembourg','Luxembourg','Luxemburgo','Europe/Luxembourg'),
 ('esch sur alzette','Esch-sur-Alzette','Luxemburgo','Europe/Luxembourg'),
 ('differdange','Differdange','Luxemburgo','Europe/Luxembourg'),
 ('tchequia','Tchéquia','Tchéquia','Europe/Prague'),
 ('chequia','Chéquia','Tchéquia','Europe/Prague'),
 ('czechia','Czechia','Tchéquia','Europe/Prague'),
 ('praga','Praga','Tchéquia','Europe/Prague'),
 ('prague','Prague','Tchéquia','Europe/Prague'),
 ('brno','Brno','Tchéquia','Europe/Prague'),
 ('ostrava','Ostrava','Tchéquia','Europe/Prague'),
 ('plzen','Plzeň','Tchéquia','Europe/Prague'),
 ('irlanda','Irlanda','Irlanda','Europe/Dublin'),
 ('ireland','Ireland','Irlanda','Europe/Dublin'),
 ('dublin','Dublin','Irlanda','Europe/Dublin'),
 ('dublim','Dublim','Irlanda','Europe/Dublin'),
 ('cork','Cork','Irlanda','Europe/Dublin'),
 ('galway','Galway','Irlanda','Europe/Dublin'),
 ('limerick','Limerick','Irlanda','Europe/Dublin'),
 ('espanha','Espanha','Espanha','Europe/Madrid'),
 ('espana','España','Espanha','Europe/Madrid'),
 ('spain','Spain','Espanha','Europe/Madrid'),
 ('madrid','Madrid','Espanha','Europe/Madrid'),
 ('barcelona','Barcelona','Espanha','Europe/Madrid'),
 ('valencia','Valência','Espanha','Europe/Madrid'),
 ('sevilha','Sevilha','Espanha','Europe/Madrid'),
 ('sevilla','Sevilla','Espanha','Europe/Madrid'),
 ('malaga','Málaga','Espanha','Europe/Madrid'),
 ('bilbao','Bilbao','Espanha','Europe/Madrid'),
 ('zaragoza','Zaragoza','Espanha','Europe/Madrid'),
 ('alicante','Alicante','Espanha','Europe/Madrid'),
 ('marbella','Marbella','Espanha','Europe/Madrid'),
 ('palma','Palma','Espanha','Europe/Madrid'),
 ('ibiza','Ibiza','Espanha','Europe/Madrid'),
 ('mexico','México','México','America/Mexico_City'),
 ('cidade do mexico','Cidade do México','México','America/Mexico_City'),
 ('ciudad de mexico','Ciudad de México','México','America/Mexico_City'),
 ('guadalajara','Guadalajara','México','America/Mexico_City'),
 ('monterrey','Monterrey','México','America/Mexico_City'),
 ('puebla','Puebla','México','America/Mexico_City'),
 ('cancun','Cancún','México','America/Mexico_City'),
 ('tijuana','Tijuana','México','America/Mexico_City'),
 ('merida','Mérida','México','America/Mexico_City'),
 ('queretaro','Querétaro','México','America/Mexico_City'),
 ('argentina','Argentina','Argentina','America/Argentina/Buenos_Aires'),
 ('buenos aires','Buenos Aires','Argentina','America/Argentina/Buenos_Aires'),
 ('cordoba argentina','Córdoba Argentina','Argentina','America/Argentina/Buenos_Aires'),
 ('rosario','Rosario','Argentina','America/Argentina/Buenos_Aires'),
 ('mendoza','Mendoza','Argentina','America/Argentina/Buenos_Aires'),
 ('la plata','La Plata','Argentina','America/Argentina/Buenos_Aires'),
 ('mar del plata','Mar del Plata','Argentina','America/Argentina/Buenos_Aires'),
 ('bariloche','Bariloche','Argentina','America/Argentina/Buenos_Aires'),
 ('italia','Itália','Itália','Europe/Rome'),
 ('italy','Italy','Itália','Europe/Rome'),
 ('roma','Roma','Itália','Europe/Rome'),
 ('rome','Rome','Itália','Europe/Rome'),
 ('milao','Milão','Itália','Europe/Rome'),
 ('milano','Milano','Itália','Europe/Rome'),
 ('milan','Milan','Itália','Europe/Rome'),
 ('napoles','Nápoles','Itália','Europe/Rome'),
 ('napoli','Napoli','Itália','Europe/Rome'),
 ('turim','Turim','Itália','Europe/Rome'),
 ('torino','Torino','Itália','Europe/Rome'),
 ('florenca','Florença','Itália','Europe/Rome'),
 ('firenze','Firenze','Itália','Europe/Rome'),
 ('veneza','Veneza','Itália','Europe/Rome'),
 ('venezia','Venezia','Itália','Europe/Rome'),
 ('bolonha','Bolonha','Itália','Europe/Rome'),
 ('bologna','Bologna','Itália','Europe/Rome'),
 ('france','France','França','Europe/Paris'),
 ('paris','Paris','França','Europe/Paris'),
 ('lyon','Lyon','França','Europe/Paris'),
 ('marselha','Marselha','França','Europe/Paris');
INSERT OR IGNORE INTO fusos_lugar (chave,nome,pais,fuso) VALUES
 ('marseille','Marseille','França','Europe/Paris'),
 ('toulouse','Toulouse','França','Europe/Paris'),
 ('nice','Nice','França','Europe/Paris'),
 ('bordeaux','Bordeaux','França','Europe/Paris'),
 ('nantes','Nantes','França','Europe/Paris'),
 ('lille','Lille','França','Europe/Paris'),
 ('estrasburgo','Estrasburgo','França','Europe/Paris'),
 ('strasbourg','Strasbourg','França','Europe/Paris'),
 ('alemanha','Alemanha','Alemanha','Europe/Berlin'),
 ('germany','Germany','Alemanha','Europe/Berlin'),
 ('deutschland','Deutschland','Alemanha','Europe/Berlin'),
 ('berlim','Berlim','Alemanha','Europe/Berlin'),
 ('berlin','Berlin','Alemanha','Europe/Berlin'),
 ('munique','Munique','Alemanha','Europe/Berlin'),
 ('munchen','München','Alemanha','Europe/Berlin'),
 ('munich','Munich','Alemanha','Europe/Berlin'),
 ('frankfurt','Frankfurt','Alemanha','Europe/Berlin'),
 ('hamburgo','Hamburgo','Alemanha','Europe/Berlin'),
 ('hamburg','Hamburg','Alemanha','Europe/Berlin'),
 ('colonia','Colônia','Alemanha','Europe/Berlin'),
 ('koln','Köln','Alemanha','Europe/Berlin'),
 ('stuttgart','Stuttgart','Alemanha','Europe/Berlin'),
 ('dusseldorf','Düsseldorf','Alemanha','Europe/Berlin'),
 ('suica','Suíça','Suíça','Europe/Zurich'),
 ('switzerland','Switzerland','Suíça','Europe/Zurich'),
 ('zurique','Zurique','Suíça','Europe/Zurich'),
 ('zurich','Zürich','Suíça','Europe/Zurich'),
 ('genebra','Genebra','Suíça','Europe/Zurich'),
 ('geneve','Genève','Suíça','Europe/Zurich'),
 ('geneva','Geneva','Suíça','Europe/Zurich'),
 ('basileia','Basileia','Suíça','Europe/Zurich'),
 ('basel','Basel','Suíça','Europe/Zurich'),
 ('berna','Berna','Suíça','Europe/Zurich'),
 ('bern','Bern','Suíça','Europe/Zurich'),
 ('lausanne','Lausanne','Suíça','Europe/Zurich'),
 ('lugano','Lugano','Suíça','Europe/Zurich'),
 ('japao','Japão','Japão','Asia/Tokyo'),
 ('japan','Japan','Japão','Asia/Tokyo'),
 ('toquio','Tóquio','Japão','Asia/Tokyo'),
 ('tokyo','Tokyo','Japão','Asia/Tokyo'),
 ('osaka','Osaka','Japão','Asia/Tokyo'),
 ('nagoya','Nagoya','Japão','Asia/Tokyo'),
 ('quioto','Quioto','Japão','Asia/Tokyo'),
 ('kyoto','Kyoto','Japão','Asia/Tokyo'),
 ('australia','Austrália','Austrália','Australia/Sydney'),
 ('sydney','Sydney','Austrália','Australia/Sydney'),
 ('melbourne','Melbourne','Austrália','Australia/Sydney'),
 ('brisbane','Brisbane','Austrália','Australia/Sydney'),
 ('canberra','Canberra','Austrália','Australia/Sydney'),
 ('gold coast','Gold Coast','Austrália','Australia/Sydney'),
 ('newcastle australia','Newcastle Australia','Austrália','Australia/Sydney'),
 ('perth','Perth','Austrália','Australia/Perth'),
 ('emirados','Emirados','Emirados Árabes','Asia/Dubai'),
 ('dubai','Dubai','Emirados Árabes','Asia/Dubai'),
 ('abu dhabi','Abu Dhabi','Emirados Árabes','Asia/Dubai'),
 ('dubai emirados','Dubai Emirados','Emirados Árabes','Asia/Dubai');
INSERT OR IGNORE INTO settings (key,value) VALUES
 ('form_idiomas','pt,en,es'),
 ('form_titulo_en','Health questionnaire — Luca Ternes'),
 ('form_intro_en','Take your time. This is what I use to build your plan before our call.'),
 ('form_agradecimento_en','Got everything. I will review your answers and message you on WhatsApp to set up the call.'),
 ('form_titulo_es','Anamnesis — Luca Ternes'),
 ('form_intro_es','Tómate tu tiempo. Esto es lo que uso para armar tu plan antes de nuestra llamada.'),
 ('form_agradecimento_es','Recibí todo. Voy a revisar tus respuestas y te escribo por WhatsApp para agendar la llamada.'),
 ('refeicoes_padrao','Café da manhã|Lanche (manhã)|Almoço|Lanche (tarde)|Jantar|Ceia'),
 ('postit',''),
 ('postit_atualizado','');
INSERT OR IGNORE INTO wa_templates (chave,nome,modo,evento,corpo,antecedencia_h,hora_envio,posicao) VALUES
 ('anamnese_link','Mandar o formulário de anamnese','semi','','Oi {primeiro_nome}! Antes da nossa conversa, preenche esse formulário pra mim: {link_anamnese}',0,'',14);
CREATE TABLE IF NOT EXISTS inbody (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  paciente_id INTEGER NOT NULL,
  data TEXT NOT NULL,
  hora TEXT,
  peso REAL,
  massa_muscular REAL,
  gordura_kg REAL,
  gordura_pct REAL,
  gordura_visceral REAL,
  obs TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_inbody_pac ON inbody(paciente_id, data);
INSERT OR IGNORE INTO settings (key,value) VALUES
 ('inbody_ativo_padrao','0'),
 ('inbody_modelo','H30'),
 ('inbody_rodape','@lucaternes.nutri   |   (53) 99908-7613   |   lucaternes.nutri@gmail.com   |   Rua Barão de Cotegipe, 433 - Sala 1203 - Edifício Porto de Gale - Rio Grande/RS'),
 ('inbody_texto_peso','É o total do corpo, formado por água, proteínas, minerais e gordura.'),
 ('inbody_texto_musculo','Quantidade de músculo do corpo — quanto maior, mais força e melhor aparência física.'),
 ('inbody_texto_gordura','É a quantidade total de gordura no corpo (sob a pele, entre órgãos ou entre músculos).'),
 ('inbody_texto_percentual','Proporção de gordura em relação ao peso total. Ideal: homens 10% a 20%, mulheres 18% a 28%.'),
 ('inbody_texto_visceral','Gordura entre os órgãos. Em excesso, aumenta o risco de doenças; valores acima de 10 são preocupantes.');
ALTER TABLE pacientes ADD COLUMN inbody_ativo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pacientes ADD COLUMN inbody_modelo TEXT;
ALTER TABLE pacientes ADD COLUMN inbody_plano TEXT;
INSERT OR IGNORE INTO settings (key,value) VALUES
 ('form_dominio','https://form.lucaternes.com.br');
